---
- include: install-epel.yaml
  when:
    - os_family == "RedHat"
    - not offline_mode_enabled

- include: install-redhat.yaml
  when: os_family == "RedHat"

- include: install-suse.yaml
  when: os_family == "Suse"

- include: install-flatcar.yaml
  when: os_family == "Flatcar"

- include: install-debian.yaml
  when: os_family == "Debian"

- include: config.yaml
