---
- include: repo-redhat.yaml
  when:
    - os_family == "RedHat"
    - not offline_mode_enabled
- include: repo-redhat-offline.yaml
  when:
    - os_family == "RedHat"
    - offline_mode_enabled
- include: repo-suse.yaml
  when: os_family == "Suse"
- include: repo-debian.yaml
  when: os_family == "Debian"
